routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DenunciasAController;
use App\Http\Controllers\DenunciasMController;
use App\Http\Controllers\LandingPage;
use App\Http\Controllers\MensajeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ValoracionesController;
use App\Mail\denunciaProducto;
use App\Models\Empleats;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    Auth::guard('web');
    $user = Socialite::driver('google')->user();
    $userExists = Empleats::where('email', $user->email)->first();
    if ($userExists){
        Auth::login($userExists);
        return redirect('/welcome');
    }
    return redirect('/');
});


Route::view('/', 'auth.login');
Route::get('/welcome', function () {
    return view('welcome');
});

Route::resource('user', UserController::class);
Route::resource('empleat', \App\Http\Controllers\EmpleatsController::class);
Route::resource('product', ProductController::class);
Route::resource('mensaje', MensajeController::class);
Route::resource('valoracion', ValoracionesController::class);
Route::resource('denunciaM', DenunciasMController::class);
Route::resource('denunciaProducto', DenunciasAController::class);
Route::resource('categoria', \App\Http\Controllers\CategoriasController::class);

Route::get('logoutUser', [LoginController::class, 'logout'])->name('logoutUser');
Route::get('/delete/{id}', [\App\Http\Controllers\UserController::class,'destroy']);
Route::get('/deleteProduct/{id}', [\App\Http\Controllers\ProductController::class,'destroy']);
Route::get('/deleteDenunciaA/{id}/{tipo}', [\App\Http\Controllers\DenunciasAController::class,'destroy']);
Route::get('/deleteDenunciaM/{id}/{tipo}', [\App\Http\Controllers\DenunciasMController::class,'destroy']);
Route::get('/deleteMensaje/{id}', [\App\Http\Controllers\MensajeController::class,'destroy']);
Route::get('/deleteEmpleado/{id}', [\App\Http\Controllers\EmpleatsController::class,'destroy']);
Route::get('/deleteValoracion/{id}', [\App\Http\Controllers\ValoracionesController::class,'destroy']);


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

resources/views/partials/footer.blade.php
<!-- Footer Start -->

<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" >BatoiPOP</a>. Pagina mantenida por
                <a class="text-primary">Carlos, Catalina y Manu</a>
            </p>
        </div>
    </div>
</div>


<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Contact Javascript File -->
<script src="mail/jqBootstrapValidation.min.js"></script>
<script src="mail/contact.js"></script>

<!-- Template Javascript -->
<script src="js/main.js"></script>
</body>

</html>

resources/views/partials/header.blade.php
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <title>BATOIPOP</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="/img/favicon.ico" rel="icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>
<!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <p class="text-body mr-3">Modo ADMINISTRADOR</p>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">
                    <button class="dropdown-item" type="button"><i class="bi bi-person"></i>{{Auth::user()->name}}</button>
                    <a class="dropdown-item" href="/logoutUser">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="{{route('user.index')}}"  class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Batoi</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">POP</span>
            </a>
        </div>


    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->

<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">BATOI</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">POP</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{{route('user.index')}}" class="nav-item nav-link ">Users</a>
                        <a href="{{route('empleat.index')}}" class="nav-item nav-link ">Empleados</a>
                        <a href="{{route('product.index')}}" class="nav-item nav-link">Productos</a>
                        <a href="{{route('denunciaProducto.index')}}" class="nav-item nav-link">Denuncias Artículos</a>
                        <a href="{{route('denunciaM.index')}}" class="nav-item nav-link">Denuncias Mensajes</a>
                        <a href="{{route('categoria.index')}}" class="nav-item nav-link">Categorías</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->