routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DenunciasAController;
use App\Http\Controllers\DenunciasMController;
use App\Http\Controllers\LandingPage;
use App\Http\Controllers\MensajeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ValoracionesController;
use App\Mail\denunciaProducto;
use App\Models\Empleats;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    Auth::guard('web');
    $user = Socialite::driver('google')->user();
    $userExists = Empleats::where('email', $user->email)->first();
    if ($userExists){
        Auth::login($userExists);
        return redirect('/welcome');
    }
    return redirect('/');
});


Route::view('/', 'auth.login');
Route::get('/welcome', function () {
    return view('welcome');
});

Route::resource('user', UserController::class);
Route::resource('empleat', \App\Http\Controllers\EmpleatsController::class);
Route::resource('product', ProductController::class);
Route::resource('mensaje', MensajeController::class);
Route::resource('valoracion', ValoracionesController::class);
Route::resource('denunciaM', DenunciasMController::class);
Route::resource('denunciaProducto', DenunciasAController::class);
Route::resource('categoria', \App\Http\Controllers\CategoriasController::class);

Route::get('logoutUser', [LoginController::class, 'logout'])->name('logoutUser');
Route::get('/delete/{id}', [\App\Http\Controllers\UserController::class,'destroy']);
Route::get('/deleteProduct/{id}', [\App\Http\Controllers\ProductController::class,'destroy']);
Route::get('/deleteDenunciaA/{id}/{tipo}', [\App\Http\Controllers\DenunciasAController::class,'destroy']);
Route::get('/deleteDenunciaM/{id}/{tipo}', [\App\Http\Controllers\DenunciasMController::class,'destroy']);
Route::get('/deleteMensaje/{id}', [\App\Http\Controllers\MensajeController::class,'destroy']);
Route::get('/deleteEmpleado/{id}', [\App\Http\Controllers\EmpleatsController::class,'destroy']);
Route::get('/deleteValoracion/{id}', [\App\Http\Controllers\ValoracionesController::class,'destroy']);


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
    public function producto()
    {
        return $this->hasMany(Product::class,'user_id','id');
    }
    public function productosComprados()
    {
        return $this->hasMany(Product::class,'comprador_id','id');
    }
    public function DenunciasM()
    {
        return $this->hasMany(DenunciaM::class,'user_id','id');
    }
    public function DenunciasA()
    {
        return $this->hasMany(DenunciaA::class,'user_id','id');
    }
    public function valoracion()
    {
        return $this->hasMany(Valoracion::class, 'user_id', 'id');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::get();
        return response()->json($user, 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User();
        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->pass = $request->get('password');
        $user->save();
        return response()->json($user, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return response()->json($user, 200);
    }




    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $postArray = $request->all();
        $user = User::find($postArray['id']);
        $user->name = $postArray['name'];
        $user->email =$postArray['email'];
        $user->ubicacion =$postArray['ubi'];
        $user->save();
        return  response()->json($user, 200);
        //$user->img = $request->get('img');
        //$user->ubicacion = $request->get('ubicacion');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return response()->json($user, 204);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\denunciaProducto;
use App\Models\DenunciaA;
use App\Models\DenunciaM;
use App\Models\Product;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'ASC')->paginate(20);
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show', compact('user', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return back();
    }
}

resources/views/users/index.blade.php
@include('partials.header')
<div class="container">
    <div class="row justify-content-center">
        <h1>Tabla Usuarios BatoiPOP</h1>
    </div>
</div>
<section class="py-5">
    <div class="container">
            <table class="table"  >
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Id</th><th scope="col">Name</th><th scope="col">Email</th><th scope="col">Actions</th>
                </tr>
                </thead>
                @if(!empty($users))
                    <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                <a class="crud" href="/delete/{{ $user->id }}"><i class="bi bi-trash"></i></a>
                                <a class="crud" href="{{route('product.show', $user->id)}}"><i class="bi bi-bag"></i></a>
                                <a class="crud" href="{{route('mensaje.show', $user->id)}}"><i class="bi bi-chat-left"></i></a>
                                <a class="crud" href="{{route('valoracion.show', $user->id)}}"><i class="bi bi-star"></i></a>
                                <a class="crud" href="{{route('user.show', $user->id)}}"><i class="bi bi-eye"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                @endif
            </table>
        <div class="d-flex justify-content-center">
            {{ $users->links() }}
        </div>
    </div>
</section>

@include('partials.footer')

resources/views/users/show.blade.php
@include('partials.header')

<section class="section about-section gray-bg" id="about">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-lg-6">
                <div class="about-text go-to">
                    <h3 class="dark-color">{{$user->name}}</h3>
                    <div class="row about-list">
                        <div class="col-md-6">
                            <div class="media">
                                <b>User Id</b>
                                <p>: {{$user->id}}</p>
                            </div>
                            <div class="media">
                                <b>Email: </b>
                                <p>{{$user->email}}</p>
                            </div>
                            <!--<div class="media">
                                <iframe src="{{$user->ubicacion}}" style="margin-bottom:20px;  width:300px; height:200px;" allowfullscreen="" loading="lazy"></iframe>
                            </div>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="about-avatar">
                    <img src="{{$user->img}}" style="height: 300px; width: 300px;">
                </div>
            </div>
        </div>
        <div class="counter">
            <div class="row">
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="500" data-speed="500">{{count($user->producto)}}</h6>
                        <p class="m-0px font-w-600">Productos</p>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="150" data-speed="150">{{count($user->productosComprados)}}</h6>
                        <p class="m-0px font-w-600">Productos Comprados</p>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="850" data-speed="850">{{count($user->denunciasM)+count($user->denunciasA)}}</h6>
                        <p class="m-0px font-w-600">Denuncias</p>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        @if(empty($user->valoracion->avg('valoracion')))
                            <p class="count" data-to="190" data-speed="190">No tiene valoraciones</p>
                        @else
                            <h6 class="count h2" data-to="190" data-speed="190">{{round($user->valoracion->avg('valoracion'),1)}}</h6>
                        @endif
                        <p class="m-0px font-w-600">Valoracion</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@include('partials.footer')