routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\DenunciasAController;
use App\Http\Controllers\DenunciasMController;
use App\Http\Controllers\LandingPage;
use App\Http\Controllers\MensajeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ValoracionesController;
use App\Mail\denunciaProducto;
use App\Models\Empleats;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login-google', function () {
    return Socialite::driver('google')->redirect();
});

Route::get('/google-callback', function () {
    Auth::guard('web');
    $user = Socialite::driver('google')->user();
    $userExists = Empleats::where('email', $user->email)->first();
    if ($userExists){
        Auth::login($userExists);
        return redirect('/welcome');
    }
    return redirect('/');
});


Route::view('/', 'auth.login');
Route::get('/welcome', function () {
    return view('welcome');
});

Route::resource('user', UserController::class);
Route::resource('empleat', \App\Http\Controllers\EmpleatsController::class);
Route::resource('product', ProductController::class);
Route::resource('mensaje', MensajeController::class);
Route::resource('valoracion', ValoracionesController::class);
Route::resource('denunciaM', DenunciasMController::class);
Route::resource('denunciaProducto', DenunciasAController::class);
Route::resource('categoria', \App\Http\Controllers\CategoriasController::class);

Route::get('logoutUser', [LoginController::class, 'logout'])->name('logoutUser');
Route::get('/delete/{id}', [\App\Http\Controllers\UserController::class,'destroy']);
Route::get('/deleteProduct/{id}', [\App\Http\Controllers\ProductController::class,'destroy']);
Route::get('/deleteDenunciaA/{id}/{tipo}', [\App\Http\Controllers\DenunciasAController::class,'destroy']);
Route::get('/deleteDenunciaM/{id}/{tipo}', [\App\Http\Controllers\DenunciasMController::class,'destroy']);
Route::get('/deleteMensaje/{id}', [\App\Http\Controllers\MensajeController::class,'destroy']);
Route::get('/deleteEmpleado/{id}', [\App\Http\Controllers\EmpleatsController::class,'destroy']);
Route::get('/deleteValoracion/{id}', [\App\Http\Controllers\ValoracionesController::class,'destroy']);


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    public function producto()
    {
        return $this->hasMany(Product::class,'category_id','id');
    }
}

resources/views/categories/create.blade.php
@include('partials.header')
<div class="d-flex d-flex justify-content-center vh-100">
    <form action="{{route('categoria.store')}}" method='POST' enctype="multipart/form-data">
        <h1>Create Categoría</h1>
        <br>
        @csrf
        <div class="form-group">
            <label for="nombre">Nombre Categoría:</label>
            <input type="text" name="nombre" id="nombre" class="form-control" placeholder="Escribe el nombre aquí" value="{{old('nombre')}}">
            @if ($errors->has('nombre'))
                <div class="text-danger">
                    {{ $errors->first('nombre') }}
                </div>
            @endif
        </div>
        <div class="form-group">
            <label for="descripcion">Descripción:</label>
            <textarea type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Escribe la descripcion aquí" rows="4" cols="50">{{old('descripcion')}}</textarea>
            @if ($errors->has('descripcion'))
                <div class="text-danger">
                    {{ $errors->first('descripcion') }}
                </div>
            @endif
        </div>
        <div class="form-group">
            <label for="file">Imagen</label>
            <input type="file" name="img" value="{{old('img')}}">
            @if ($errors->has('img'))
                <div class="text-danger">
                    {{ $errors->first('img') }}
                </div>
            @endif
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary" style="padding:8px 100px;margin-top:25px;">Crear Categoría</button>
        </div>
    </form>
</div>
@include('partials.footer')

resources/views/categories/edit.blade.php
@include('partials.header')
<div class="d-flex d-flex justify-content-center vh-100">
    <form action="{{route('categoria.update', $categoria->id)}}" method='POST' enctype="multipart/form-data">
        <h1>Edit Categoría</h1>
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="nombre">Nombre Categoría:</label>
            <input type="text" name="nombre" id="nombre" class="form-control" placeholder="Escribe el nombre aquí" value="{{$errors->any() ?  old('nombre') : $categoria->nombre}}">
            @if ($errors->has('nombre'))
                <div class="text-danger">
                    {{ $errors->first('nombre') }}
                </div>
            @endif
        </div>
        <div class="form-group">
            <label for="descripcion">descripción:</label>
            <textarea type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Escribe la descripcion aquí" rows="4" cols="50">{{$errors->any() ?  old('descripcion') : $categoria->descripcion}}</textarea>
            @if ($errors->has('descripcion'))
                <div class="text-danger">
                    {{ $errors->first('descripcion') }}
                </div>
            @endif
        </div>
        <div class="form-group">
            <label for="file">Imagen</label>
            <img style="height:90px" src="{{$errors->any() ?  old('img') : $categoria->img }}">
            <input type="file" name="img">
            @if ($errors->has('img'))
                <div class="text-danger">
                    {{ $errors->first('img') }}
                </div>
            @endif
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary" style="padding:8px 100px;margin-top:25px;">Edit Categoría</button>
        </div>
    </form>
</div>
@include('partials.footer')

resources/views/categories/index.blade.php
@include('partials.header')
<div class="container">
    <div class="row justify-content-center">
        <h1>Categorias BatoiPOP</h1>
    </div>
</div>
<section class="py-5">
    <div class="container">
        <table class="table"  >
            <thead class="thead-dark">
            <tr>
                <th scope="col">Id</th><th scope="col">Imagen</th><th scope="col">Categoría</th><th scope="col">Total Productos</th><th scope="col">Descripción</th><th scope="col">Actions <a href="{{route('categoria.create')}}" class="btn btn-sm btn-dark">New</a></th>
            </tr>
            </thead>
            @if(!empty($categorias))
                <tbody>
                @foreach ($categorias as $categoria)
                    <tr>
                        <td>{{ $categoria->id }}</td>
                        <td> <img src="{{$categoria->img}}" style="height:90px"></td>
                        <td>{{ $categoria->nombre }}</td>
                        <td>{{count($categoria->producto)}}</td>
                        <td>{{ $categoria->descripcion }}</td>
                        <td>
                            <a class="crud" href="{{route('categoria.edit', $categoria->id)}}"><i class="bi bi-pencil"></i></a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            @endif
        </table>
        <div class="d-flex justify-content-center">
            {{ $categorias->links() }}
        </div>
    </div>
</section>

@include('partials.footer')